### ISSUE TITLE
Unable to go from Skills to Settings or Home page

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/chat.susi.ai#1036]
**Actual Behaviour**
If a user is on the skills page ([skills.susi.ai](skills.susi.ai)), they cannot go to the settings page upon clicking settings in the dropdown menu, because they are redirected to [https://skills.susi.ai/settings](https://skills.susi.ai/settings) rather than [https://chat.susi.ai/settings](https://chat.susi.ai/settings). The page they are being redirected to only allows user to change the theme. Users cannot also go to the home page upon clicking the Susi logo in the navbar.

**Expected Behaviour**

Clicking Settings should take user to [https://skills.susi.ai/settings](https://skills.susi.ai/settings) if they are currently on the Skills page. Clicking on the logo will take them to [skills.susi.ai](skills.susi.ai), the page they are currently on

**Steps to reproduce it**

Visit Skills page and then click on Settings in the menu, or the Susi logo in navbar

**Screenshots of the issue**

<img width="1267" alt="screen shot 2018-01-13 at 2 06 09 am" src="https://user-images.githubusercontent.com/24372680/34894357-17c903b0-f807-11e7-8ae0-427fc1828e47.png">

**Would you like to work on the issue?**

Yes

**Comment by Remorax** [comment]
Um, I think the behaviour is correct as it is. The [skills website](https://skills.susi.ai/) is different from the main [chat website](https://chat.susi.ai/). Each has its own settings page, and its own repo. So skills is not just a "page", rather its' a separate website. So clicking on the logo in the skills website redirects to the skills home page like it should and vice versa for the chat website. There are also links in the dropdown to chat from skills, and from chat to skills.
So all in all, I think this issue is unnecessary and it can be closed. Please take up some other issue. Cheers 😄
