### ISSUE TITLE
Upgrade MUI

### ISSUE THREAD

**Issue by pranshuchittora** [fossasia/chat.susi.ai#1865]
**Actual Behaviour**
The current version of MUI which we are using is 0.18.
**Expected Behaviour**
Let's upgrade to MUI @latest. I know it's difficult but still, let's do it.
**Steps to reproduce it**

https://github.com/fossasia/chat.susi.ai/blob/7abb7ed0a1f2b9b4b20635b6cfde4a1fb17c0796/package.json#L28

**Would you like to work on the issue?**
Yup, just an approval required. :+1:

**Comment by AakashMallik** [comment]
Not required right now. @pranshuchittora

**Comment by pranshuchittora** [comment]
Oh, Can you pls tell me the reason for not doing it ??

**Comment by AakashMallik** [comment]
Because it is not a pressing issue and our views are working perfectly fine. With the number of PRs that are currently pending to get merged, upgrading a view library would bleed havoc in the repo given the fact that all the import statements need to be changed when you upgrade that 3rd party npm module. Is his enough reason for not doing it? :innocent:

**Comment by AakashMallik** [comment]
Even the react version is outdated, but you won't we are not upgrading it as of now for a reason. I guess you get my point.

**Comment by pranshuchittora** [comment]
I completely got your point. But at some point, you need to upgrade. 
- Every version update improves performance.
- It would create a huge mess if you upgrade from v1 to v10.

I prefer upgrading ASAP by referring the changelogs & removing deprecated API / Features.

**Comment by AakashMallik** [comment]
I am against this because we don't have a stable repo right now. If you make the change right now and if it gets merged, then everyone would end up spending an hour or two fixing merge conflicts. And why would shifting from 1 to 10 be difficult? We exactly know where the components are being used, you just need to find them and replace them as mentioned in the documentation.

**Comment by AakashMallik** [comment]
It is not something you can do in a single PR over a night of coffee rush. It would probably need another WIP branch and worked up parallelly as the repo progresses. But our hands are full as we are dealing with other upgradations right now. Check the list of PRs to get an idea of what the repo is going through.

**Comment by AakashMallik** [comment]
@akshatnitd  @Akshat-Jain @anshumanv Let us know your opinion on this.
