### ISSUE TITLE
Show the status of message delivery using tick or clock symbols similar to android client

### ISSUE THREAD

**Issue by uday96** [fossasia/chat.susi.ai#382]
**Actual Behaviour**

As of now, webchat only shows a loading gif while fetching response from server. 

**Expected Behaviour**

We can also show a clock symbol for the query waiting for response and a tick for other messages like in android client

**Screenshots of the issue**

![tick](https://user-images.githubusercontent.com/13276887/27815327-f16b9dac-60a0-11e7-8387-7e7409435bb3.png)

![clock](https://user-images.githubusercontent.com/13276887/27815329-f5bffdee-60a0-11e7-8b46-4e25d74f837b.png)

**Would you like to work on the issue?**

Yes

**Comment by uday96** [comment]
@rishiraj824 @isuruAb @madhavrathi Please suggest if this is needed or the current implementation with only loading gif is enough?

**Comment by isuruAb** [comment]
when you are going to show clock and right symbols ?

**Comment by uday96** [comment]
1. Show a clock symbol until the call to server is made
2. Once the call to server is made, show a tick indicating that the server recieved the query

**Comment by rishiraj824** [comment]
How are you going to differentiate or calculate the time between the Message appearing in the chat (which is an action of `createMessage()` ) and the server call being made?

**Comment by uday96** [comment]
Create message will display the user message. So by default it renders with a clock. Until createSUSIMessage is called where the server call is being made. But that would be very minimal time :/

**Comment by rishiraj824** [comment]
Yes, the thing is the user won't even be able to see the clock if we go by this.

**Comment by uday96** [comment]
@rishiraj824 Yes, got your point :+1: Pinged the android people regarding this. Will get back with their implementation

**Comment by uday96** [comment]
@rishiraj824 @isuruAb So I confirmed with the android people, They are displaying the clock symbol until the response from server is fetched i.e along with the loading gif.
So this would give reasonable amount of time to display the symbol too.
Should I proceed with this?

**Comment by rishiraj824** [comment]
@uday96 but in that case the user will only think that their message hasn't been delivered, which it has right?

**Comment by uday96** [comment]
@rishiraj824 Yes. That's the general interpretation of the clock symbol. But this can be another interpretation too. Was asking your suggestion for the same.
@chiragw15 Please provide your input too.

**Comment by chiragw15** [comment]
See, one way you can implement is display clock before call is made, single tick when call is made but client is waiting for server response and double click when response from server came and is displayed to the user. 
Other way can to display clock when user has send message and tick when he received message.
In android app we have used the second way. Basically we are removing the double tick. Earlier there were action types in app in which the query was not sent to server. So in that case displaying single tick would not have been right since server never received message. Therefore, Tick in susi android app indicates that user has received message from Susi and clock indicates that user's query is still being interpreted and worked on be it sending it to server or interpreting it in app itself

**Comment by rishiraj824** [comment]
@chiragw15 Okay if that's the interpretation of the clock and the tick, we can proceed with it. :+1:
