### ISSUE TITLE
Improve thumbs functionality and move thumbs next to time/date, also keep it in conversation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#512]
Why are the thumbs up/down disappearing when a user continues the conversation. Please keep the thumbs there. But: Move the to the right of the time/date in one line.

I also see that there is a number e.g. 6 thumbs up. How come?

Thumbs up or down should only be available for individual usage and they will help us in training the machine learning algorithms later.

![screenshot from 2017-07-17 15-39-18](https://user-images.githubusercontent.com/1583873/28270593-5306b0e6-6b06-11e7-905c-a11183bcdb10.png)

**Comment by madhavrathi** [comment]
@mariobehling The thumbs are for the most recent response received, and we can move them to right of date and time. Also, the number shows that how good is the response, this gives the user an idea how people have reacted towards the response. If you feel like we should remove these data and just show the thumbs up or down, we can proceed likewise. But I strongly feel providing number is a better approach.
Thanks

**Comment by madhavrathi** [comment]
@rishiraj824 @uday96 @isuruAb Please give your views on this
Thanks

**Comment by isuruAb** [comment]
@madhavrathi  since number of feedbacks are still less that 10 it is okay when it is moretham 100 or 1000 it will be a trouble to keep the value on the chat bubble. as I think it would be good if we could hide the number .

**Comment by uday96** [comment]
Okay, we can remove the displaying feedback part and align the thumbs to the right. 
But if we keep the thumbs for the entire conversation, then when do we send the feedback back to the server? In the current implementation, we store the feedback locally for the latest message and send it to the server when a new message is entered to reduce the number of api calls to server because for every feedback i.e for every message we need to make an api call. Incase we show thumbs for the entire conversation, then the user can first like a message and then dislike it later so we cant make a direct api call upon a thumbs up or thumbs down button click. So when do we send the feedback back to server?

**Comment by mariobehling** [comment]
> But if we keep the thumbs for the entire conversation, then when do we send the feedback back to the server?

Yes.

> In the current implementation, we store the feedback locally for the latest message and send it to the server when a new message is entered to reduce the number of api calls to server because for every feedback i.e for every message we need to make an api call.

Yes, it can stay that way, can't it?

> Incase we show thumbs for the entire conversation, then the user can first like a message and then dislike it later so we cant make a direct api call upon a thumbs up or thumbs down button click. 

Disable this. Once the user has given a feedback, it should not be possible to change. That is it.

**Comment by madhavrathi** [comment]
@uday96 So we will have to edit the method, I think you made the implementation for setting feedback, can we edit the way suggested ?
I will hide the numbers in next PR and align the thumbs to right.
Thanks

**Comment by uday96** [comment]
@mariobehling Okay got it. I can change the thumbs functionality accordingly :+1:
