### ISSUE TITLE
If there are two PCs in the same network the chat shows the same history

### ISSUE THREAD

**Issue by mariobehling** [fossasia/chat.susi.ai#564]
I used the PC in the network and asked questions. Now another PC opened SUSI in anonymous mode. Susi now shows my chat.

Expected: Every device has its own history in anonymous mode.

**Comment by uday96** [comment]
@mariobehling The client calls http://api.susi.ai/susi/memory.json which returns a list of history messages and renders the history accordingly.
For logged in users the history is parsed based on email id from `/data/susi/email_EMAIL`
For anonymous users the history is parsed based on IP from `/data/susi/host_IP`

So since the two PCs were connected to same network, I think the IP recorded was the same. Hence same history was being shown for both.

This should be handled on the server side. Should I create a issue on susi_server?

**Comment by uday96** [comment]
Opened an issue on server - https://github.com/fossasia/susi_server/issues/412

@Orbiter Please guide.

**Comment by mariobehling** [comment]
Should be solved on the server.
