### ISSUE TITLE
Settings: Improve Save button actions

### ISSUE THREAD

**Issue by hpdang** [fossasia/chat.susi.ai#819]
On the settings tabs please change the save button action as follows:
* Show save button in active stage only when something can be saved
* Show save button inactive when there is nothing to save
* Stay on the same tab after user presses "Save"

![screenshot from 2017-09-22 11-07-14](https://user-images.githubusercontent.com/1658742/30737393-b0a5838a-9f86-11e7-8ccb-b07562b9c209.png)

**Comment by hkedia321** [comment]
I would like to work on it :+1:

**Comment by hkedia321** [comment]
In the settings page, the **"SAVE CHANGES" button looks redundant** for the following tabs:
1. Server Settings (when logged in)
2. Account Settings (when logged in)
3. Connect to SUSI Hardware 

This is because we have to edit the settings in a popup having its own save button. So the Save button on the settings page has no use.
**Can we remove these buttons on these tabs ?**
Please provide me suggestions on this.
Thanks.

**Comment by zamhaq** [comment]
@mariobehling @rishiraj824 this issue can be closed?

**Comment by rishiraj824** [comment]
closing via #836
